[workspace]
resolver = "2" # As of Nov 2021, rust doesn't use new resolver if you don't specify this

members = [
    "xb15_core",
    "tof",
    "led_matrix_test",
    "gif_parser"
]

[profile.release]
lto = true
