[package]
name = "testing"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
gif_parser = { path = "../gif_parser" }
new_composer = { path = "../new_composer" }
clap = { version = "3.2.20", features = ["derive"] }
