[package]
name = "gif_parser"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
gif = "0.11.4"
gif-dispose = "3.1.1"
imgref = "1.9.2"
image = "0.24.3"
clap = { version = "3.2.20", features = ["derive"] }
